[package]
name = "neptune"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.65"
chrono = "0.4.22"
clap = "3.2.22"
dialoguer = { version = "0.10.2", features = ["fuzzy-select"] }
genpdf = { version = "0.2.0", features = ["images"] }
ordinal = "0.3.2"
strum = "0.24.1"
strum_macros = "0.24.3"
task_log = "0.1.4"
