[package]
name = "neptune"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.65"
chrono = "0.4.22"
genpdf = { version = "0.2.0", features = ["images"] }
ordinal = "0.3.2"
task_log = "0.1.4"
